version: 1.0.0.{build}
skip_tags: true
before_build:  
  - nuget restore
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
environment:
    COVERALLS_REPO_TOKEN:  
        secure: HeQR7z0Shrsw7TJBV7X3Bm9cBRb83JHdenWn25BXDQSVjD1xPxdcasi3vE/5My8G
after_test: 
  - Source\SimpleRetry.UnitTests\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -mergeoutput -register:user -target:"Source\SimpleRetry.UnitTests\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" "-targetargs:""Source\SimpleRetry.UnitTests\bin\Debug\SimpleRetry.UnitTests.dll"" /noshadow" -output:opencoverCoverage.xml
  - Source\SimpleRetry.UnitTests\packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken %COVERALLS_REPO_TOKEN% --commitBranch %APPVEYOR_REPO_BRANCH% 
deploy:
- provider: NuGet
  api_key:
    secure: sgFlZQ6SSawwtiKcN23uO3hdwEGvy8M4hA8ye2iTAPdmz4gByofx2ZljpJHZ+Pm3
  on:
    branch: master