version: 2.0.0.{build}
skip_tags: true
configuration: Release
before_build:  
  - nuget restore Source\SimpleRetry.sln
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: Source\SimpleRetry.sln
  publish_nuget: true
  #verbosity: detailed
environment:
    COVERALLS_REPO_TOKEN:  
        secure: HeQR7z0Shrsw7TJBV7X3Bm9cBRb83JHdenWn25BXDQSVjD1xPxdcasi3vE/5My8G
after_test: 
  - Source\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"Source\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" "-targetargs:""Source\SimpleRetry.UnitTests\bin\Release\SimpleRetry.UnitTests.dll""" -output:opencoverCoverage.xml -filter:"+[*]* -[*]*FluentAssertions*" -excludebyfile:"*SampleUsage.cs;*Tests.cs"
  - Source\packages\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken %COVERALLS_REPO_TOKEN% --commitBranch %APPVEYOR_REPO_BRANCH% 
deploy:
- provider: NuGet
  api_key:
    secure: sgFlZQ6SSawwtiKcN23uO3hdwEGvy8M4hA8ye2iTAPdmz4gByofx2ZljpJHZ+Pm3
  on:
    branch: master